-- =============================================================
-- Wanderpass — country stamp library seed (auto-generated)
-- Source: scripts/countries.mjs · regenerate: node scripts/generate-seed.mjs
-- Run AFTER schema.sql, in Supabase → SQL Editor.
-- =============================================================

insert into countries (code, name_th, name_en, continent, flag_emoji, stamp_svg_url) values
  ('TH', 'ไทย', 'Thailand', 'Asia', '🇹🇭', '/stamps/th.svg'),
  ('JP', 'ญี่ปุ่น', 'Japan', 'Asia', '🇯🇵', '/stamps/jp.svg'),
  ('KR', 'เกาหลีใต้', 'South Korea', 'Asia', '🇰🇷', '/stamps/kr.svg'),
  ('KP', 'เกาหลีเหนือ', 'North Korea', 'Asia', '🇰🇵', '/stamps/kp.svg'),
  ('CN', 'จีน', 'China', 'Asia', '🇨🇳', '/stamps/cn.svg'),
  ('TW', 'ไต้หวัน', 'Taiwan', 'Asia', '🇹🇼', '/stamps/tw.svg'),
  ('HK', 'ฮ่องกง', 'Hong Kong', 'Asia', '🇭🇰', '/stamps/hk.svg'),
  ('MO', 'มาเก๊า', 'Macau', 'Asia', '🇲🇴', '/stamps/mo.svg'),
  ('SG', 'สิงคโปร์', 'Singapore', 'Asia', '🇸🇬', '/stamps/sg.svg'),
  ('MY', 'มาเลเซีย', 'Malaysia', 'Asia', '🇲🇾', '/stamps/my.svg'),
  ('ID', 'อินโดนีเซีย', 'Indonesia', 'Asia', '🇮🇩', '/stamps/id.svg'),
  ('PH', 'ฟิลิปปินส์', 'Philippines', 'Asia', '🇵🇭', '/stamps/ph.svg'),
  ('VN', 'เวียดนาม', 'Vietnam', 'Asia', '🇻🇳', '/stamps/vn.svg'),
  ('LA', 'ลาว', 'Laos', 'Asia', '🇱🇦', '/stamps/la.svg'),
  ('KH', 'กัมพูชา', 'Cambodia', 'Asia', '🇰🇭', '/stamps/kh.svg'),
  ('MM', 'เมียนมา', 'Myanmar', 'Asia', '🇲🇲', '/stamps/mm.svg'),
  ('BN', 'บรูไน', 'Brunei', 'Asia', '🇧🇳', '/stamps/bn.svg'),
  ('IN', 'อินเดีย', 'India', 'Asia', '🇮🇳', '/stamps/in.svg'),
  ('NP', 'เนปาล', 'Nepal', 'Asia', '🇳🇵', '/stamps/np.svg'),
  ('BT', 'ภูฏาน', 'Bhutan', 'Asia', '🇧🇹', '/stamps/bt.svg'),
  ('BD', 'บังกลาเทศ', 'Bangladesh', 'Asia', '🇧🇩', '/stamps/bd.svg'),
  ('LK', 'ศรีลังกา', 'Sri Lanka', 'Asia', '🇱🇰', '/stamps/lk.svg'),
  ('PK', 'ปากีสถาน', 'Pakistan', 'Asia', '🇵🇰', '/stamps/pk.svg'),
  ('MV', 'มัลดีฟส์', 'Maldives', 'Asia', '🇲🇻', '/stamps/mv.svg'),
  ('AF', 'อัฟกานิสถาน', 'Afghanistan', 'Asia', '🇦🇫', '/stamps/af.svg'),
  ('KZ', 'คาซัคสถาน', 'Kazakhstan', 'Asia', '🇰🇿', '/stamps/kz.svg'),
  ('UZ', 'อุซเบกิสถาน', 'Uzbekistan', 'Asia', '🇺🇿', '/stamps/uz.svg'),
  ('MN', 'มองโกเลีย', 'Mongolia', 'Asia', '🇲🇳', '/stamps/mn.svg'),
  ('AE', 'สหรัฐอาหรับเอมิเรตส์', 'United Arab Emirates', 'Asia', '🇦🇪', '/stamps/ae.svg'),
  ('SA', 'ซาอุดีอาระเบีย', 'Saudi Arabia', 'Asia', '🇸🇦', '/stamps/sa.svg'),
  ('QA', 'กาตาร์', 'Qatar', 'Asia', '🇶🇦', '/stamps/qa.svg'),
  ('KW', 'คูเวต', 'Kuwait', 'Asia', '🇰🇼', '/stamps/kw.svg'),
  ('BH', 'บาห์เรน', 'Bahrain', 'Asia', '🇧🇭', '/stamps/bh.svg'),
  ('OM', 'โอมาน', 'Oman', 'Asia', '🇴🇲', '/stamps/om.svg'),
  ('JO', 'จอร์แดน', 'Jordan', 'Asia', '🇯🇴', '/stamps/jo.svg'),
  ('IL', 'อิสราเอล', 'Israel', 'Asia', '🇮🇱', '/stamps/il.svg'),
  ('LB', 'เลบานอน', 'Lebanon', 'Asia', '🇱🇧', '/stamps/lb.svg'),
  ('TR', 'ตุรกี', 'Turkey', 'Asia', '🇹🇷', '/stamps/tr.svg'),
  ('IR', 'อิหร่าน', 'Iran', 'Asia', '🇮🇷', '/stamps/ir.svg'),
  ('IQ', 'อิรัก', 'Iraq', 'Asia', '🇮🇶', '/stamps/iq.svg'),
  ('GE', 'จอร์เจีย', 'Georgia', 'Asia', '🇬🇪', '/stamps/ge.svg'),
  ('AM', 'อาร์เมเนีย', 'Armenia', 'Asia', '🇦🇲', '/stamps/am.svg'),
  ('AZ', 'อาเซอร์ไบจาน', 'Azerbaijan', 'Asia', '🇦🇿', '/stamps/az.svg'),
  ('GB', 'สหราชอาณาจักร', 'United Kingdom', 'Europe', '🇬🇧', '/stamps/gb.svg'),
  ('FR', 'ฝรั่งเศส', 'France', 'Europe', '🇫🇷', '/stamps/fr.svg'),
  ('DE', 'เยอรมนี', 'Germany', 'Europe', '🇩🇪', '/stamps/de.svg'),
  ('IT', 'อิตาลี', 'Italy', 'Europe', '🇮🇹', '/stamps/it.svg'),
  ('ES', 'สเปน', 'Spain', 'Europe', '🇪🇸', '/stamps/es.svg'),
  ('PT', 'โปรตุเกส', 'Portugal', 'Europe', '🇵🇹', '/stamps/pt.svg'),
  ('NL', 'เนเธอร์แลนด์', 'Netherlands', 'Europe', '🇳🇱', '/stamps/nl.svg'),
  ('BE', 'เบลเยียม', 'Belgium', 'Europe', '🇧🇪', '/stamps/be.svg'),
  ('LU', 'ลักเซมเบิร์ก', 'Luxembourg', 'Europe', '🇱🇺', '/stamps/lu.svg'),
  ('CH', 'สวิตเซอร์แลนด์', 'Switzerland', 'Europe', '🇨🇭', '/stamps/ch.svg'),
  ('AT', 'ออสเตรีย', 'Austria', 'Europe', '🇦🇹', '/stamps/at.svg'),
  ('IE', 'ไอร์แลนด์', 'Ireland', 'Europe', '🇮🇪', '/stamps/ie.svg'),
  ('DK', 'เดนมาร์ก', 'Denmark', 'Europe', '🇩🇰', '/stamps/dk.svg'),
  ('SE', 'สวีเดน', 'Sweden', 'Europe', '🇸🇪', '/stamps/se.svg'),
  ('NO', 'นอร์เวย์', 'Norway', 'Europe', '🇳🇴', '/stamps/no.svg'),
  ('FI', 'ฟินแลนด์', 'Finland', 'Europe', '🇫🇮', '/stamps/fi.svg'),
  ('IS', 'ไอซ์แลนด์', 'Iceland', 'Europe', '🇮🇸', '/stamps/is.svg'),
  ('PL', 'โปแลนด์', 'Poland', 'Europe', '🇵🇱', '/stamps/pl.svg'),
  ('CZ', 'เช็กเกีย', 'Czechia', 'Europe', '🇨🇿', '/stamps/cz.svg'),
  ('SK', 'สโลวาเกีย', 'Slovakia', 'Europe', '🇸🇰', '/stamps/sk.svg'),
  ('HU', 'ฮังการี', 'Hungary', 'Europe', '🇭🇺', '/stamps/hu.svg'),
  ('GR', 'กรีซ', 'Greece', 'Europe', '🇬🇷', '/stamps/gr.svg'),
  ('HR', 'โครเอเชีย', 'Croatia', 'Europe', '🇭🇷', '/stamps/hr.svg'),
  ('SI', 'สโลวีเนีย', 'Slovenia', 'Europe', '🇸🇮', '/stamps/si.svg'),
  ('RO', 'โรมาเนีย', 'Romania', 'Europe', '🇷🇴', '/stamps/ro.svg'),
  ('BG', 'บัลแกเรีย', 'Bulgaria', 'Europe', '🇧🇬', '/stamps/bg.svg'),
  ('RS', 'เซอร์เบีย', 'Serbia', 'Europe', '🇷🇸', '/stamps/rs.svg'),
  ('UA', 'ยูเครน', 'Ukraine', 'Europe', '🇺🇦', '/stamps/ua.svg'),
  ('RU', 'รัสเซีย', 'Russia', 'Europe', '🇷🇺', '/stamps/ru.svg'),
  ('EE', 'เอสโตเนีย', 'Estonia', 'Europe', '🇪🇪', '/stamps/ee.svg'),
  ('LV', 'ลัตเวีย', 'Latvia', 'Europe', '🇱🇻', '/stamps/lv.svg'),
  ('LT', 'ลิทัวเนีย', 'Lithuania', 'Europe', '🇱🇹', '/stamps/lt.svg'),
  ('MT', 'มอลตา', 'Malta', 'Europe', '🇲🇹', '/stamps/mt.svg'),
  ('CY', 'ไซปรัส', 'Cyprus', 'Europe', '🇨🇾', '/stamps/cy.svg'),
  ('MC', 'โมนาโก', 'Monaco', 'Europe', '🇲🇨', '/stamps/mc.svg'),
  ('VA', 'นครรัฐวาติกัน', 'Vatican City', 'Europe', '🇻🇦', '/stamps/va.svg'),
  ('AD', 'อันดอร์รา', 'Andorra', 'Europe', '🇦🇩', '/stamps/ad.svg'),
  ('AL', 'แอลเบเนีย', 'Albania', 'Europe', '🇦🇱', '/stamps/al.svg'),
  ('BA', 'บอสเนียและเฮอร์เซโกวีนา', 'Bosnia and Herzegovina', 'Europe', '🇧🇦', '/stamps/ba.svg'),
  ('ME', 'มอนเตเนโกร', 'Montenegro', 'Europe', '🇲🇪', '/stamps/me.svg'),
  ('MK', 'มาซิโดเนียเหนือ', 'North Macedonia', 'Europe', '🇲🇰', '/stamps/mk.svg'),
  ('US', 'สหรัฐอเมริกา', 'United States', 'North America', '🇺🇸', '/stamps/us.svg'),
  ('CA', 'แคนาดา', 'Canada', 'North America', '🇨🇦', '/stamps/ca.svg'),
  ('MX', 'เม็กซิโก', 'Mexico', 'North America', '🇲🇽', '/stamps/mx.svg'),
  ('CU', 'คิวบา', 'Cuba', 'North America', '🇨🇺', '/stamps/cu.svg'),
  ('JM', 'จาเมกา', 'Jamaica', 'North America', '🇯🇲', '/stamps/jm.svg'),
  ('DO', 'สาธารณรัฐโดมินิกัน', 'Dominican Republic', 'North America', '🇩🇴', '/stamps/do.svg'),
  ('CR', 'คอสตาริกา', 'Costa Rica', 'North America', '🇨🇷', '/stamps/cr.svg'),
  ('PA', 'ปานามา', 'Panama', 'North America', '🇵🇦', '/stamps/pa.svg'),
  ('GT', 'กัวเตมาลา', 'Guatemala', 'North America', '🇬🇹', '/stamps/gt.svg'),
  ('BS', 'บาฮามาส', 'Bahamas', 'North America', '🇧🇸', '/stamps/bs.svg'),
  ('BZ', 'เบลีซ', 'Belize', 'North America', '🇧🇿', '/stamps/bz.svg'),
  ('HN', 'ฮอนดูรัส', 'Honduras', 'North America', '🇭🇳', '/stamps/hn.svg'),
  ('NI', 'นิการากัว', 'Nicaragua', 'North America', '🇳🇮', '/stamps/ni.svg'),
  ('SV', 'เอลซัลวาดอร์', 'El Salvador', 'North America', '🇸🇻', '/stamps/sv.svg'),
  ('BR', 'บราซิล', 'Brazil', 'South America', '🇧🇷', '/stamps/br.svg'),
  ('AR', 'อาร์เจนตินา', 'Argentina', 'South America', '🇦🇷', '/stamps/ar.svg'),
  ('CL', 'ชิลี', 'Chile', 'South America', '🇨🇱', '/stamps/cl.svg'),
  ('PE', 'เปรู', 'Peru', 'South America', '🇵🇪', '/stamps/pe.svg'),
  ('CO', 'โคลอมเบีย', 'Colombia', 'South America', '🇨🇴', '/stamps/co.svg'),
  ('EC', 'เอกวาดอร์', 'Ecuador', 'South America', '🇪🇨', '/stamps/ec.svg'),
  ('BO', 'โบลิเวีย', 'Bolivia', 'South America', '🇧🇴', '/stamps/bo.svg'),
  ('UY', 'อุรุกวัย', 'Uruguay', 'South America', '🇺🇾', '/stamps/uy.svg'),
  ('PY', 'ปารากวัย', 'Paraguay', 'South America', '🇵🇾', '/stamps/py.svg'),
  ('VE', 'เวเนซุเอลา', 'Venezuela', 'South America', '🇻🇪', '/stamps/ve.svg'),
  ('EG', 'อียิปต์', 'Egypt', 'Africa', '🇪🇬', '/stamps/eg.svg'),
  ('MA', 'โมร็อกโก', 'Morocco', 'Africa', '🇲🇦', '/stamps/ma.svg'),
  ('ZA', 'แอฟริกาใต้', 'South Africa', 'Africa', '🇿🇦', '/stamps/za.svg'),
  ('KE', 'เคนยา', 'Kenya', 'Africa', '🇰🇪', '/stamps/ke.svg'),
  ('TZ', 'แทนซาเนีย', 'Tanzania', 'Africa', '🇹🇿', '/stamps/tz.svg'),
  ('ET', 'เอธิโอเปีย', 'Ethiopia', 'Africa', '🇪🇹', '/stamps/et.svg'),
  ('NG', 'ไนจีเรีย', 'Nigeria', 'Africa', '🇳🇬', '/stamps/ng.svg'),
  ('GH', 'กานา', 'Ghana', 'Africa', '🇬🇭', '/stamps/gh.svg'),
  ('TN', 'ตูนิเซีย', 'Tunisia', 'Africa', '🇹🇳', '/stamps/tn.svg'),
  ('DZ', 'แอลจีเรีย', 'Algeria', 'Africa', '🇩🇿', '/stamps/dz.svg'),
  ('MU', 'มอริเชียส', 'Mauritius', 'Africa', '🇲🇺', '/stamps/mu.svg'),
  ('SC', 'เซเชลส์', 'Seychelles', 'Africa', '🇸🇨', '/stamps/sc.svg'),
  ('NA', 'นามิเบีย', 'Namibia', 'Africa', '🇳🇦', '/stamps/na.svg'),
  ('BW', 'บอตสวานา', 'Botswana', 'Africa', '🇧🇼', '/stamps/bw.svg'),
  ('ZW', 'ซิมบับเว', 'Zimbabwe', 'Africa', '🇿🇼', '/stamps/zw.svg'),
  ('UG', 'ยูกันดา', 'Uganda', 'Africa', '🇺🇬', '/stamps/ug.svg'),
  ('RW', 'รวันดา', 'Rwanda', 'Africa', '🇷🇼', '/stamps/rw.svg'),
  ('SN', 'เซเนกัล', 'Senegal', 'Africa', '🇸🇳', '/stamps/sn.svg'),
  ('MG', 'มาดากัสการ์', 'Madagascar', 'Africa', '🇲🇬', '/stamps/mg.svg'),
  ('AU', 'ออสเตรเลีย', 'Australia', 'Oceania', '🇦🇺', '/stamps/au.svg'),
  ('NZ', 'นิวซีแลนด์', 'New Zealand', 'Oceania', '🇳🇿', '/stamps/nz.svg'),
  ('FJ', 'ฟิจิ', 'Fiji', 'Oceania', '🇫🇯', '/stamps/fj.svg'),
  ('PG', 'ปาปัวนิวกินี', 'Papua New Guinea', 'Oceania', '🇵🇬', '/stamps/pg.svg'),
  ('WS', 'ซามัว', 'Samoa', 'Oceania', '🇼🇸', '/stamps/ws.svg'),
  ('TO', 'ตองงา', 'Tonga', 'Oceania', '🇹🇴', '/stamps/to.svg'),
  ('VU', 'วานูอาตู', 'Vanuatu', 'Oceania', '🇻🇺', '/stamps/vu.svg'),
  ('PF', 'เฟรนช์โปลินีเซีย', 'French Polynesia', 'Oceania', '🇵🇫', '/stamps/pf.svg'),
  ('NC', 'นิวแคลิโดเนีย', 'New Caledonia', 'Oceania', '🇳🇨', '/stamps/nc.svg')
on conflict (code) do update set
  name_th = excluded.name_th,
  name_en = excluded.name_en,
  continent = excluded.continent,
  flag_emoji = excluded.flag_emoji;
-- note: stamp_svg_url is NOT overwritten on conflict, so admin edits are preserved.
