// Shared country catalog for Wanderpass.
// Used by generate-stamps.mjs (SVG stamps) and generate-seed.mjs (SQL seed).
//
// Each entry: [ISO-3166-1 alpha-2 code, Thai name, English name, continent].
// Flag emoji is derived from the code automatically — no need to type it.
// Admin can add/replace stamp art later from the Admin screen.

export const CONTINENTS = {
  asia: "เอเชีย",
  europe: "ยุโรป",
  africa: "แอฟริกา",
  north_america: "อเมริกาเหนือ",
  south_america: "อเมริกาใต้",
  oceania: "โอเชียเนีย",
};

// continent keys stored in DB (English) → Thai shown in UI via CONTINENTS map
export const COUNTRIES = [
  // ---------- Asia ----------
  ["TH", "ไทย", "Thailand", "Asia"],
  ["JP", "ญี่ปุ่น", "Japan", "Asia"],
  ["KR", "เกาหลีใต้", "South Korea", "Asia"],
  ["KP", "เกาหลีเหนือ", "North Korea", "Asia"],
  ["CN", "จีน", "China", "Asia"],
  ["TW", "ไต้หวัน", "Taiwan", "Asia"],
  ["HK", "ฮ่องกง", "Hong Kong", "Asia"],
  ["MO", "มาเก๊า", "Macau", "Asia"],
  ["SG", "สิงคโปร์", "Singapore", "Asia"],
  ["MY", "มาเลเซีย", "Malaysia", "Asia"],
  ["ID", "อินโดนีเซีย", "Indonesia", "Asia"],
  ["PH", "ฟิลิปปินส์", "Philippines", "Asia"],
  ["VN", "เวียดนาม", "Vietnam", "Asia"],
  ["LA", "ลาว", "Laos", "Asia"],
  ["KH", "กัมพูชา", "Cambodia", "Asia"],
  ["MM", "เมียนมา", "Myanmar", "Asia"],
  ["BN", "บรูไน", "Brunei", "Asia"],
  ["IN", "อินเดีย", "India", "Asia"],
  ["NP", "เนปาล", "Nepal", "Asia"],
  ["BT", "ภูฏาน", "Bhutan", "Asia"],
  ["BD", "บังกลาเทศ", "Bangladesh", "Asia"],
  ["LK", "ศรีลังกา", "Sri Lanka", "Asia"],
  ["PK", "ปากีสถาน", "Pakistan", "Asia"],
  ["MV", "มัลดีฟส์", "Maldives", "Asia"],
  ["AF", "อัฟกานิสถาน", "Afghanistan", "Asia"],
  ["KZ", "คาซัคสถาน", "Kazakhstan", "Asia"],
  ["UZ", "อุซเบกิสถาน", "Uzbekistan", "Asia"],
  ["MN", "มองโกเลีย", "Mongolia", "Asia"],
  ["AE", "สหรัฐอาหรับเอมิเรตส์", "United Arab Emirates", "Asia"],
  ["SA", "ซาอุดีอาระเบีย", "Saudi Arabia", "Asia"],
  ["QA", "กาตาร์", "Qatar", "Asia"],
  ["KW", "คูเวต", "Kuwait", "Asia"],
  ["BH", "บาห์เรน", "Bahrain", "Asia"],
  ["OM", "โอมาน", "Oman", "Asia"],
  ["JO", "จอร์แดน", "Jordan", "Asia"],
  ["IL", "อิสราเอล", "Israel", "Asia"],
  ["LB", "เลบานอน", "Lebanon", "Asia"],
  ["TR", "ตุรกี", "Turkey", "Asia"],
  ["IR", "อิหร่าน", "Iran", "Asia"],
  ["IQ", "อิรัก", "Iraq", "Asia"],
  ["GE", "จอร์เจีย", "Georgia", "Asia"],
  ["AM", "อาร์เมเนีย", "Armenia", "Asia"],
  ["AZ", "อาเซอร์ไบจาน", "Azerbaijan", "Asia"],

  // ---------- Europe ----------
  ["GB", "สหราชอาณาจักร", "United Kingdom", "Europe"],
  ["FR", "ฝรั่งเศส", "France", "Europe"],
  ["DE", "เยอรมนี", "Germany", "Europe"],
  ["IT", "อิตาลี", "Italy", "Europe"],
  ["ES", "สเปน", "Spain", "Europe"],
  ["PT", "โปรตุเกส", "Portugal", "Europe"],
  ["NL", "เนเธอร์แลนด์", "Netherlands", "Europe"],
  ["BE", "เบลเยียม", "Belgium", "Europe"],
  ["LU", "ลักเซมเบิร์ก", "Luxembourg", "Europe"],
  ["CH", "สวิตเซอร์แลนด์", "Switzerland", "Europe"],
  ["AT", "ออสเตรีย", "Austria", "Europe"],
  ["IE", "ไอร์แลนด์", "Ireland", "Europe"],
  ["DK", "เดนมาร์ก", "Denmark", "Europe"],
  ["SE", "สวีเดน", "Sweden", "Europe"],
  ["NO", "นอร์เวย์", "Norway", "Europe"],
  ["FI", "ฟินแลนด์", "Finland", "Europe"],
  ["IS", "ไอซ์แลนด์", "Iceland", "Europe"],
  ["PL", "โปแลนด์", "Poland", "Europe"],
  ["CZ", "เช็กเกีย", "Czechia", "Europe"],
  ["SK", "สโลวาเกีย", "Slovakia", "Europe"],
  ["HU", "ฮังการี", "Hungary", "Europe"],
  ["GR", "กรีซ", "Greece", "Europe"],
  ["HR", "โครเอเชีย", "Croatia", "Europe"],
  ["SI", "สโลวีเนีย", "Slovenia", "Europe"],
  ["RO", "โรมาเนีย", "Romania", "Europe"],
  ["BG", "บัลแกเรีย", "Bulgaria", "Europe"],
  ["RS", "เซอร์เบีย", "Serbia", "Europe"],
  ["UA", "ยูเครน", "Ukraine", "Europe"],
  ["RU", "รัสเซีย", "Russia", "Europe"],
  ["EE", "เอสโตเนีย", "Estonia", "Europe"],
  ["LV", "ลัตเวีย", "Latvia", "Europe"],
  ["LT", "ลิทัวเนีย", "Lithuania", "Europe"],
  ["MT", "มอลตา", "Malta", "Europe"],
  ["CY", "ไซปรัส", "Cyprus", "Europe"],
  ["MC", "โมนาโก", "Monaco", "Europe"],
  ["VA", "นครรัฐวาติกัน", "Vatican City", "Europe"],
  ["AD", "อันดอร์รา", "Andorra", "Europe"],
  ["AL", "แอลเบเนีย", "Albania", "Europe"],
  ["BA", "บอสเนียและเฮอร์เซโกวีนา", "Bosnia and Herzegovina", "Europe"],
  ["ME", "มอนเตเนโกร", "Montenegro", "Europe"],
  ["MK", "มาซิโดเนียเหนือ", "North Macedonia", "Europe"],

  // ---------- North America ----------
  ["US", "สหรัฐอเมริกา", "United States", "North America"],
  ["CA", "แคนาดา", "Canada", "North America"],
  ["MX", "เม็กซิโก", "Mexico", "North America"],
  ["CU", "คิวบา", "Cuba", "North America"],
  ["JM", "จาเมกา", "Jamaica", "North America"],
  ["DO", "สาธารณรัฐโดมินิกัน", "Dominican Republic", "North America"],
  ["CR", "คอสตาริกา", "Costa Rica", "North America"],
  ["PA", "ปานามา", "Panama", "North America"],
  ["GT", "กัวเตมาลา", "Guatemala", "North America"],
  ["BS", "บาฮามาส", "Bahamas", "North America"],
  ["BZ", "เบลีซ", "Belize", "North America"],
  ["HN", "ฮอนดูรัส", "Honduras", "North America"],
  ["NI", "นิการากัว", "Nicaragua", "North America"],
  ["SV", "เอลซัลวาดอร์", "El Salvador", "North America"],

  // ---------- South America ----------
  ["BR", "บราซิล", "Brazil", "South America"],
  ["AR", "อาร์เจนตินา", "Argentina", "South America"],
  ["CL", "ชิลี", "Chile", "South America"],
  ["PE", "เปรู", "Peru", "South America"],
  ["CO", "โคลอมเบีย", "Colombia", "South America"],
  ["EC", "เอกวาดอร์", "Ecuador", "South America"],
  ["BO", "โบลิเวีย", "Bolivia", "South America"],
  ["UY", "อุรุกวัย", "Uruguay", "South America"],
  ["PY", "ปารากวัย", "Paraguay", "South America"],
  ["VE", "เวเนซุเอลา", "Venezuela", "South America"],

  // ---------- Africa ----------
  ["EG", "อียิปต์", "Egypt", "Africa"],
  ["MA", "โมร็อกโก", "Morocco", "Africa"],
  ["ZA", "แอฟริกาใต้", "South Africa", "Africa"],
  ["KE", "เคนยา", "Kenya", "Africa"],
  ["TZ", "แทนซาเนีย", "Tanzania", "Africa"],
  ["ET", "เอธิโอเปีย", "Ethiopia", "Africa"],
  ["NG", "ไนจีเรีย", "Nigeria", "Africa"],
  ["GH", "กานา", "Ghana", "Africa"],
  ["TN", "ตูนิเซีย", "Tunisia", "Africa"],
  ["DZ", "แอลจีเรีย", "Algeria", "Africa"],
  ["MU", "มอริเชียส", "Mauritius", "Africa"],
  ["SC", "เซเชลส์", "Seychelles", "Africa"],
  ["NA", "นามิเบีย", "Namibia", "Africa"],
  ["BW", "บอตสวานา", "Botswana", "Africa"],
  ["ZW", "ซิมบับเว", "Zimbabwe", "Africa"],
  ["UG", "ยูกันดา", "Uganda", "Africa"],
  ["RW", "รวันดา", "Rwanda", "Africa"],
  ["SN", "เซเนกัล", "Senegal", "Africa"],
  ["MG", "มาดากัสการ์", "Madagascar", "Africa"],

  // ---------- Oceania ----------
  ["AU", "ออสเตรเลีย", "Australia", "Oceania"],
  ["NZ", "นิวซีแลนด์", "New Zealand", "Oceania"],
  ["FJ", "ฟิจิ", "Fiji", "Oceania"],
  ["PG", "ปาปัวนิวกินี", "Papua New Guinea", "Oceania"],
  ["WS", "ซามัว", "Samoa", "Oceania"],
  ["TO", "ตองงา", "Tonga", "Oceania"],
  ["VU", "วานูอาตู", "Vanuatu", "Oceania"],
  ["PF", "เฟรนช์โปลินีเซีย", "French Polynesia", "Oceania"],
  ["NC", "นิวแคลิโดเนีย", "New Caledonia", "Oceania"],
].map(([code, nameTh, nameEn, continent]) => ({ code, nameTh, nameEn, continent }));

// Flag emoji from ISO code: each letter → regional indicator symbol.
export function flagEmoji(code) {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65));
}
